stages:
  - build

before_script:
  - export REPO_NAME=Utilities
  - export CI_PATH=~/git/gitlabCI
  - if [ -d "$CI_PATH" ]; then rm -rf $CI_PATH && mkdir -p $CI_PATH; fi
  - mkdir $CI_PATH/install
  - git clone git@github.com:NWChemEx-Project/$REPO_NAME.git $CI_PATH/$REPO_NAME

variables:
  CMAKE_OPTIONS: "-DCMAKE_PREFIX_PATH=${CI_PATH}/install -DCMAKE_INSTALL_PREFIX=${CI_PATH}/install -DCPP_GITHUB_TOKEN=\
a942e188f9c4a0d80d069b826fdb1a3e85f3fe02 -DCMAKE_C_COMPILER=gcc =DCMAKE_CXX_COMPILER=g++"
  NUM_CORES: "24"

default_build:
    stage: build
    script:
      - module load gcc-9.1.0-gcc-7.4.0-jjv2tsg cmake-3.14.2-gcc-9.1.0-jzu7ays
      - cd $CI_PATH/$REPO_NAME
      - cmake $CMAKE_OPTIONS -DBUILD_TESTS=ON --build .
      - make -j$NUM_CORES
      - ctest -VV
