stages:
  - build

before_script:
  - export REPO_NAME=Utilities
  - export CI_PATH=~/git/gitlabCI
  - if [ -d "$CI_PATH" ]; then rm -rf $CI_PATH; fi
  - mkdir -p $CI_PATH/install
  - git clone git@gitlab.com:NWChemEx-Project/Utilities.git $CI_PATH/$REPO_NAME
  - git clone https://github.com/CMakePP/CMakePackagingProject.git $CI_PATH/CMakePP

variables:
  CMAKE_OPTIONS: "-DCMAKE_PREFIX_PATH=$CI_PATH/install -DCMAKE_INSTALL_PREFIX=$CI_PATH/install -DCMAKE_C_COMPILER=gcc =DCMAKE_CXX_COMPILER=g++"
  NUM_CORES: "20"

default_build:
    tags:
      - linux,kamban
    stage: build
    script:
      - module load gcc-9.1.0-gcc-7.4.0-jjv2tsg cmake-3.14.2-gcc-9.1.0-jzu7ays
      - cd $CI_PATH/CMakePP
      - cmake $CMAKE_OPTIONS -DBUILD_TESTS=ON --build .
      - cd build
      - make install
      - cd $CI_PATH/$REPO_NAME
      - cmake $CMAKE_OPTIONS -DBUILD_TESTS=ON --build .
      - cd build
      - make -j$NUM_CORES
      - ctest -VV
