name: test container action with arguments

description: To test running an action in a container with building arguments

inputs:
  btag:  
    description: 'tag of the base image'
    required: false
    default: 'stable'
  token:
    required: true
  user:
    required: true
  env1_sh:
    required: true
  env2_sh:
    required: true
outputs:
  gcc_version: # id of output
    description: the gcc version in the image used
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.user }}
    - ${{ inputs.btag }}
    - ${{ inputs.env1_sh }}
    - ${{ inputs.env2_sh }}
