name: Update release image because of build image update

on:
  repository_dispatch:
    types: release_update
jobs:
        update_release_image:
    steps:
      - name: build and install the repo
        uses: NWChemEx-CI-test/.github/.github/workflows/image-c-cpp_tmpl.yaml@master
        with: 
          repo: Utilities
          clang-build: false
          gcc-build: true
          ninja_build: true
          test: true
          install: true
        secrets: inherit
      - name: Send build update repo dispatches
        uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: [TensorWrapper, PluginPlay]
          type: build_update
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

