name: Build and test with docker image

on:
        #########pull_request:
  push:
    branches:
      - master

jobs:
  build-with-gcc:
    uses: NWChemEx-CI-test/.github/.github/workflows/image-c-cpp_tmpl.yaml@master
    with: 
      repo: Utilities
      clang-build: false
      gcc-build: true
      ninja_build: true
      test: true
      install: true
    secrets: inherit 
    #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
    #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
