name: Integration test with the stable building image

on:
  repository_dispatch:
    types: integ_test
        #workflow_run:
        #  workflows: [Build and test with dev]
        #  types:
        #    - completed

jobs:
  Integration_test:
    uses: NWChemEx-CI-test/.github/.github/workflows/build_test-dev_tmpl.yaml@master
    with:
      repo: Utilities
      clang-build: false
      gcc-build: true
      ninja_build: true
      test: true
      integration_test: true
      install: true
      build_image_tag: stable
    secrets: inherit
    #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
    #DOCKER_PAT: {{ secrets.DOCKER_PAT }}

# Update other repos
  Update-repo_dispatch:
    runs-on: ubuntu-latest
    needs: Integration_test
    strategy:
      matrix:
        repos: [TensorWrapper, PluginPlay]
    steps:
      - uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: ${{ matrix.repos }}
          type: build_update
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          from_repo: Utilities
          initial_repo: Utilities
          #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
          #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
