name: Test sending client_payload
on:
  workflow_dispatch:

jobs:
  client_payload_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [PluginPlay, TensorWrapper]
    steps:
      - name: Send release dispatches to target repos
        uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: ${{ matrix.target_repo }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          type: build_update
          cl_pl:
            simde_all: true
            scfgradients_all: true
            nwchemex_all: true
          #secrets: inherit
            #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
            #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
