name: Test of send a repo dispatch
on:
        #workflow_dispatch:
  push:
    branches: master

jobs:
  repo_dispatch_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [PluginPlay, ParallelZone]
    steps:
      - name: Send release dispatches to target repos
        uses: NWChemEx-CI-test/.github/actions/release_dispatch@master
        with:
          to_repo: ${{ matrix.target_repo }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          #secrets: inherit
            #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
            #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
