name: "Read file contents"

on: 
  push:
    branches: master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: get the version source
        run: |
          curl -L -o nwx_versions.json https://github.com/NWChemEx-Project/NWXCMake/blob/master/cmake/nwx_versions.cmake
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "nwx_versions.json"
          prop_path: "payload.blob"
      - run: |
          echo ${{ steps.json_properties.outputs.rawLines }}

