name: "Read file contents"

on: 
  push:
    branches: master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        #- name: Read file contents
        #  id: read_file
        #  uses: andstor/file-reader-action@v1
        #  with:
        #    path: ".github/workflows/example.json"
        #- name: File contents
        #  filecont: ${{ fromJSON(steps.read_file.outputs.contents) }}
        #  run: |
        #    #echo "${{ steps.read_file.outputs.contents }}"
        #    echo ${{ filecont.widget.debug }}
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".github/workflows/example.json"
      - run: |
          echo ${{steps.json_properties.outputs.widget}}
