name: "Read file contents"

on: 
  push:
    branches: master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ".github/workflows/example2.json"
      - name: File contents
        #filecont: ${{ fromJSON(steps.read_file.outputs.contents) }}
        env: ${{ fromJSON(steps.read_file.outputs.contents) }}
        run: |
          #echo "${{ steps.read_file.outputs.contents }}"
          #gccv="${{fromJSON(steps.read_file.outputs.contents)}}"
          echo "gcc_version = " ${{ env.gcc_version }}

        #- name: get properties
        #  id: json_properties
        #  uses: zoexx/github-action-json-file-properties@release
        #  with:
        #    file_path: ".github/workflows/example.json"
        #    prop_path: "widget.window"
        #- run: |
        #    echo ${{steps.json_properties.outputs.title}}
        #
