name: test container action

on:
  workflow_dispatch:

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - name: In the original container
        run: cat /etc/issue
      - name: call container action
        uses: NWChemEx-CI-test/Utilities/actions/image-action@master
        id: container-action
        with:
          btag: latest
          token: ${{ secrets.DOCKER_PAT }}
          user: ${{ github.actor }}
      - name: check gcc version
        run: |
          echo "The gcc version in the base image is " ${{steps.container-action.outputs.gcc_version}}
