name: Test Docker Image

on:
  workflow_dispatch:

jobs:
  build-image-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the image
        run: |
          docker build -t test_image -f test.Dockerfile .
          docker save -o /test_image.tar test_image
      - name: Test the image built in last step
        run: |
          docker load test_image.tar
          docker run -t test_image

