name: check the existence of an image

on:
  workflow_dispatch:

jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Check stable release image
        id: image_exists
        shell: /usr/bin/bash {0}
        run: |
          docker manifest inspect ghcr.io/nwchemex-ci-test/base_chemist:stable > /dev/null
          echo "conclusion=$?" >> "$GITHUB_OUTPUT"
      - name: Push stable release image if not exist
        if: ${{ steps.image_exists.outputs.conclusion != 0 }}
        uses: NWChemEx-CI-test/.github/actions/push_image@master
        with:
          tmp_image_name: ghcr.io/nwchemex-ci-test/base_parallelzone
          tmp_image_tag: latest
          image_name: ghcr.io/nwchemex-ci-test/base_parallelzone
          image_tag: stable
