name: "Read file contents"

on: 
  push:
    branches: master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: get the version source
        run: |
          curl -L -o nwx_versions.json https://github.com/NWChemEx-Project/NWXCMake/blob/master/cmake/nwx_versions.cmake
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "nwx_versions.json"
          prop_path: "payload.blob"
      - name: Write raw lines 
        env:
          outfile_path: rawLines.tmp
        run: |
          echo ${{ steps.json_properties.outputs.rawLines }} > "${{env.outfile_path}}"
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Convert raw lines into JSON
        uses: NWChemEx-CI-test/.github/actions/rawlines2json@master
        with:
          infile_path: rawLines.tmp
          outfile_path: package_versions.json
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: package_versions.json
      - name: put json into env
        env: ${{ fromJSON(steps.read_file.outputs.contents) }}
        run: |
          echo "gcc_version = " ${{env.gcc_version}}
