name: Test of send a repo dispatch
on:
        #workflow_dispatch:
  push:
    branches: master

jobs:
  repo_dispatch_test:
    runs-on: ubuntu-latest
    steps:
      - name: Send a repo dispatch to announce the update of the release image
        uses: NWChemEx-CI-test/.github/actions/release_dispatch@master
        with:
          repo_name: Utilities
          DOCKER_PAT: {{ secrets.DOCKER_PAT }}
          #secrets: inherit
            #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
            #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
