name: "Read file contents"

on: 
  push:
    branches: master

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "example.json"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"
