name: Rebuild building image
on:
        # Utilities uses the building image of ParallelZone, so
        # only a build_update dispatch can invoke this workflow
  repository_dispatch:
    types: build_update

jobs:
  rebuild_building:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Update the building tool image
        run: |
          docker pull ghcr.io/nwchemex-ci-test/build_parallelzone:test
          docker tag ghcr.io/nwchemex-ci-test/build_parallelzone:test ghcr.io/nwchemex-ci-test/build_utilities:test
          docker push ghcr.io/nwchemex-ci-test/build_utilities:test
      - name: Send a release update repo dispatch
        uses: NWChemEx-CI-test/.github/actions/repo_dispatch@master
        with:
          to_repo: Utilities
          type: release_update
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          from_repo: Utilities
          initial_repo: Utilities

